### ISSUE TITLE
Support use in app extensions

### ISSUE THREAD

**Issue by ZevEisenberg** [Rightpoint/BonMot#251]
See [this similar request for Anchorage](https://github.com/Raizlabs/Anchorage/pull/21#issuecomment-262791384). When I enable the `APPLICATION_EXTENSION_API_ONLY` flag, I get this:

```BonMot/Sources/UIKit/UIKit+Helpers.swift:61:26: error: 'shared' is unavailable: Use view controller based solutions where appropriate instead.
        if UIApplication.shared.delegate != nil {
                         ^~~~~~
UIKit.UIApplication:5:20: note: 'shared' has been explicitly marked unavailable here
    open class var shared: UIApplication { get }
                   ^
BonMot/Sources/UIKit/UIKit+Helpers.swift:62:34: error: 'shared' is unavailable: Use view controller based solutions where appropriate instead.
            return UIApplication.shared.preferredContentSizeCategory
                                 ^~~~~~
UIKit.UIApplication:5:20: note: 'shared' has been explicitly marked unavailable here
    open class var shared: UIApplication { get }
                   ^
```

**Comment by soundbites** [comment]
I had the same issue yesterday. I've sorta fixed with a pre-processor
```
        // `UIApplication.shared` is not a valid object in unit tests. Fall back
        // to a default value if the delegate is nil.
        // Also make UIApplication is not available in extensions
#if !TARGET_IS_EXTENSION
        if UIApplication.shared.delegate != nil {
            return UIApplication.shared.preferredContentSizeCategory
        }
#endif
        
        #if swift(>=3.0)
            return UIContentSizeCategory.large
        #else
            return UIContentSizeCategoryLarge
        #endif
```

and then setting up the `other Swift flags` with `-DTARGET_IS_EXTENSION`

**Comment by ZevEisenberg** [comment]
@soundbites don't extensions support Dynamic Type? Isn't there a global function to get the content size category, or some other way to get it in extensions? It looks like your solution would just return a constant value in extensions, if I'm reading it right.

**Comment by ZevEisenberg** [comment]
I posted a [Stack Overflow question](http://stackoverflow.com/questions/41388934/equivalent-of-uiapplication-shared-preferredcontentsizecategory-in-app-extension) on how to solve this. Looking for ways to get the extension's preferred trait collection.

**Comment by LeoNatan** [comment]
Does `UIScreen.main.preferredContentSizeCategory` return an expected value? Iirc, `UIScreen.main` is officially available in extensions.

Generally, `sharedApplication` actually exists in extensions, just artificially blocked due to how Apple have set up their extensions lifecycle. `(UIApplication.value(forKey: "sharedApplication") as! UIApplication).preferredContentSizeCategory` will give you what you want.

If no official API can give you what you need, make sure to open a bug report with Apple.

**Comment by ZevEisenberg** [comment]
@LeoNatan `UIScreen` doesn't appear to know anything about content size categories or the key window 😞

**Comment by LeoNatan** [comment]
It shouldn't know about windows, but I see it is a trait environment. What does it return?

**Comment by ZevEisenberg** [comment]
Ah, yes, it has a trait collection, and we can get a preferred trait collection from there on iOS 10+. For 9, I guess we just don't support Dynamic Type in extensions?

**Comment by LeoNatan** [comment]
Go the `(UIApplication.value(forKey: "sharedApplication") as! UIApplication).preferredContentSizeCategory` route. You will get the result you want.

**Comment by ZevEisenberg** [comment]
Needs to be App Store-safe. I'd rather not use private-ish API.

**Comment by LeoNatan** [comment]
Private is a strong word in this case. Grey area API, as I like to call it. 😄 Perhaps 10+ is good enough for dynamic type.

**Comment by LeoNatan** [comment]
Perhaps `UIScreen` had `preferredContentSizeCategory` in iOS 9, but was not officially exposed. Worth exploring.

**Comment by ZevEisenberg** [comment]
Revisiting this, I think it would be fine to support extensions only in iOS 10+.

**Comment by lammertw** [comment]
Any news on this? I'm trying to create some Siri UI extensions and it's really unfortunate that I cannot share my code that's using BonMot with my extension.

**Comment by teameh** [comment]
I thought this would be an easy thing to fix but it's not. 

As @plarson himself [noticed](https://github.com/Rightpoint/BonMot/pull/301#issuecomment-330969702), the first approach using the `NS_EXTENSION_UNAVAILABLE_IOS` flag does not work because it is not intended to be used in conditionals but only to [mark methods as unavailable for use in extensions](https://github.com/pinterest/PINRemoteImage/issues/93#issuecomment-164583598).  It's used to give you the `x has been explicitly marked unavailable here` warning. 

Approach 2 would be to follow [this article](https://davedelong.com/blog/2019/04/09/conditional-compilation-part-3/). It describes using the `APPLICATION_EXTENSION_API_ONLY` flag to check if the code is running in an extension or not. I tried to get something like that working with the podspec but I couldn't. 

```
  s.pod_target_xcconfig = {
    "BONMOT_APP_EXTENSION_NO" => "0",
    "BONMOT_APP_EXTENSION_YES" => "1",
    "BONMOT_IS_APP_EXTENSION" => "$(BONMOT_APP_EXTENSION_$(APPLICATION_EXTENSION_API_ONLY))"
  }
```

Then there's [this](https://miqu.me/blog/2016/11/28/app-extensions-xcode-and-cocoapods-omg/) 3rd approach, which would ask the users that would like to use BonMot in their extension to add it separately like: 

```
abstract_target 'App' do
  # Shared pods between App and extension, compiled with same preprocessor macros
  pod 'AFNetworking'
  ...

  target 'MyApp' do
    pod 'BonMot'
  end

  target 'MyExtension' do
    pod 'BonMot/AppExtension'
  end
end
```

Lastly there's [this](https://github.com/m1entus/MZFormSheetPresentationController/pull/75/files) approach that asks the users to add some code to their podfile. 

If you search on the 2 flags mentioned above you'll [find](https://github.com/snowplow/snowplow-objc-tracker/issues/301) more [libraries](https://github.com/pinterest/PINRemoteImage/issues/93) struggling with [this](https://github.com/m1entus/MZFormSheetPresentationController/commit/b8595065f4215b6c2679f6475a4d0dfda196169c)...

**Comment by lammertw** [comment]
I guess this issue is easily fixed by dropping support for iOS 9 correct? In that case it can just use `UIScreen.main.traitCollection.preferredContentSizeCategory`:

```
    public var bon_preferredContentSizeCategory: BonMotContentSizeCategory {
        if preferredContentSizeCategory != .unspecified {
            return preferredContentSizeCategory
        }

        return UIScreen.main.traitCollection.preferredContentSizeCategory
    }
```

Since we're almost at iOS 13 now wouldn't it be ok to just drop iOS 9 support?

**Comment by teameh** [comment]
> Since we're almost at iOS 13 now wouldn't it be ok to just drop iOS 9 support?

I agree, we're already 5 months into iOS 13.

**Comment by chepiok** [comment]
Yes forget iOS 9! Any! chance to have an official release with the fix to work in application extension?
