### ISSUE TITLE
Does not compile with a Swift Package Manager installation

### ISSUE THREAD

**Issue by mathieutozer** [Rightpoint/BonMot#387]
Here's a vanilla cross platform Xcode template with the package installed (via Xcode) and the library added to each plaftorm's target. Looks like UIKit is missing?

https://github.com/mathieutozer/BonMotTest

**Comment by ZevEisenberg** [comment]
@mathieutozer I was able to reproduce the issue in your sample project, but not in my own sample project. To save some time, would you mind posting the steps you used to create your project? I want to figure out what I'm doing differently.

**Comment by mathieutozer** [comment]
1. Xcode Version 11.3 (11C29)
2. New Project: Cross-Platform Game, default settings (Swift, SceneKit), all 4 platforms

**Comment by mathieutozer** [comment]
Noting that macOS and tvOS compile, so maybe some if os(watchOS) checks are required?

**Comment by chrisballinger** [comment]
@mathieutozer Thanks for the repro! I think the issue here is that it appears that you can `import UIKit` when targeting watchOS, but basically none of the APIs are marked available except for things like `UIColor`. My guess is that if we change this everywhere it says `if canImport(UIKit)` things will probably work as expected.

```swift
#if canImport(UIKit) && !os(watchOS)
import UIKit
```

**Comment by chrisballinger** [comment]
@mathieutozer I have a PR up that will probably fix your issue: #388
