### ISSUE TITLE
Xcode 12 supports 🔼

### ISSUE THREAD

**Issue by BeerPoldet** [Rightpoint/BonMot#394]
BonMot is an all-time perfect library. Thank you for your contribution.

Since a release of Xcode 12. Please give us a version that supports Xcode 12. Thank you.

**Comment by ZevEisenberg** [comment]
@BeerPoldet would you mind please posting what issues you're having with Xcode 12? Are there any warnings or errors that need to be addressed?

**Comment by BeerPoldet** [comment]
This is errors I found when I try to run `carthage update`

<img width="265" alt="Screen Shot 2563-09-22 at 16 23 34" src="https://user-images.githubusercontent.com/7531231/93958646-1f8a7e80-fd81-11ea-8726-d343605024d8.png">

-----

Apparently, It's a problem of Carthage and Xcode 12. This link has some comments that pointed out the way to solve this. https://github.com/Carthage/Carthage/issues/3019. And this comment helps. https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323
Thank you for your support @ZevEisenberg. ♥️ BonMot.

**Comment by chrisballinger** [comment]
I would recommend you switch to either Swift Package Manager, CocoaPods, or manual integration. I think Carthage will be a source of many headaches until it properly supports xcframeworks. There's not much library authors can do about this issue, it's just a fundamental flaw with Carthage's current approach. The workarounds posted in that thread aren't ideal and are not compatible with Apple Silicon.

The root of the issue is that "fat" binaries can only have a single slice for each individual architecture. That approach worked okay when we had only arm64 iOS devices and x86_64 iOS simulators. Soon we will have slices for arm64 iOS, arm64 iOS simulator, and x86_64 iOS simulator. The only way around that is using xcframeworks.
